name = "github-stats-auth"
main = "src/index.js"
compatibility_date = "2026-10-06"
preview_urls = false

[observability]
enabled = true

[observability.logs]
enabled = true

[vars]
ALLOWED_ORIGIN = "https://lorenzopallotta.github.io"

[[kv_namespaces]]
binding = "CARDS"
id = "4684d987ba0449f8b0a608cef5ef4ff8"

[triggers]
crons = ["0 * * * *"]